lib/views/mobile/receive/widgets/ReceiveProgress.dart, pubspec.lock
=> merge conflict fixed

ios/Flutter/Debug.xcconfig, ios/Flutter/Release.xcconfig, ios/Podfile, macos/Flutter/Flutter-Debug.xcconfig, macos/Flutter/Flutter-Release.xcconfig, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcworkspace/contents.xcworkspacedata
=> IOS config

lib/views/desktop/send/widget/DTSelectAFile.dart
---
Created  new widget called DTSelectAFile. this widget will be used in desktop send screen
=> select a file ui for desktop send screen

lib/views/desktop/send/send.dart
---
Started using SelectAFile widget and CodeGeneration Widget in desktop send screen
=> moved code to special widgets

lib/views/desktop/send/widget/DTButtonWithIcon.dart
=> new DTButtonWithIcon widget for desktop send screen

lib/views/desktop/receive/receive.dart, lib/views/desktop/send/widget/DTSelectAFile.dart
=> fixed spacings in receive and send screens for desktop

lib/config/theme/colors.dart, lib/config/theme/custom_theme.dart, lib/views/desktop/widgets/custom-app-bar.dart
=> fixed navbar background color

lib/config/theme/custom_theme.dart, lib/constants/app_constants.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widget/DTSendingProgress.dart, lib/views/desktop/widgets/DTButton.dart, lib/views/desktop/widgets/DTFileInfo.dart
=> sending progress ui widget for  desktop send screen

integration_test/client/file_transfer_test.dart
=> Add fileName to recvFile return value

.github/workflows/build.yml, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, pubspec.lock, test/widget_test.dart
=> Initial CI

lib/views/shared/send.dart
=> Add progress handler for receive file

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, lib/config/routes/routes_desktop_config.dart, lib/views/desktop/send/widget/DTSelectAFile.dart, lib/views/mobile/settings.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart, pubspec.lock, pubspec.yaml
=> Add android storage permissions. Use mobile screens for receive.

.github/workflows/build.yml, android/build.gradle, integration_test/client/file_transfer_test.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/ReceiveConfirmation.dart, lib/views/shared/receive.dart, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
=> Download confirmation and large file support

lib/views/desktop/send/send.dart, lib/views/desktop/send/widget/DTButtonLinearGradientWithIcon.dart, lib/views/desktop/send/widget/DTCodeGeneration.dart, lib/views/desktop/send/widget/DTRowGroupButton.dart, lib/views/desktop/send/widget/DTSelectAFile.dart, lib/views/desktop/send/widget/DTSendingProgress.dart, lib/views/desktop/widgets/DTFileInfo.dart
=> Fix desktop code generation UI

lib/views/desktop/send/send.dart, lib/views/desktop/send/widget/DTSendingProgress.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/ReceiveProgress.dart, lib/views/mobile/send/send.dart, lib/views/mobile/send/widgets/SelectAFileUI.dart, lib/views/mobile/send/widgets/SendingProgress.dart, lib/views/shared/progress.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart, lib/views/shared/util.dart
=> Add shared progress logic for receive/send states

README.md, lib/views/desktop/receive/receive.dart, lib/views/desktop/settings.dart, lib/views/desktop/widgets/DTButtonWithBackground.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/settings.dart, lib/views/shared/progress.dart, lib/views/shared/receive.dart, lib/views/shared/settings.dart, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner/DebugProfile.entitlements, macos/Runner/Release.entitlements
=> Add macos build support

.github/workflows/build.yml
=> Add mac builds to github workflow

lib/views/shared/util.dart
=> Add windows support

lib/config/theme/colors.dart, lib/constants/app_constants.dart, lib/main.dart, lib/views/desktop/send/widgets/DTButtonLinearGradientWithIcon.dart, lib/views/desktop/send/widgets/DTSelectAFile.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/ReceiveConfirmation.dart, lib/views/mobile/receive/widgets/ReceiveProgress.dart, lib/views/mobile/send/send.dart, lib/views/mobile/send/widgets/SendingProgress.dart, lib/views/mobile/widgets/FileInfo.dart, lib/views/shared/progress.dart, lib/views/shared/receive.dart, lib/views/shared/settings.dart, pubspec.lock, test/mobile_widget_test.dart
---
I fixed ScreenUtilInit's "sp" property in this PR. This property allows fonts to adapt different screen sizes [OP#558]. This fix was necessary to make "flutter test" pass. I did some fixings and refactoring for the unit tests as well. [OP#558]
=> [OP#558] Mobile unit test

.github/workflows/android-build.yml, .github/workflows/macos-build.yml
=> Create github releases for builds triggered by a tag

lib/constants/app_constants.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/send/send.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/send/send.dart, lib/views/shared/progress.dart
OP#622
OP#646
---
- ~[ ] New code has enough tests.~
- ~[ ] New code has enough documentation to answer "how do I use it?" and "what does it do?".~
- ~[ ] Existing documentation is up-to-date, if impacted.~
=> Sender progress improvement

.github/workflows/linux-build.yml, .github/workflows/windows-build.yml
=> Add windows and linux build workflows

lib/views/desktop/receive/receive.dart, lib/views/desktop/receive/widgets/DTReceiveProgress.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTCodeGeneration.dart, lib/views/desktop/send/widgets/DTSendingProgress.dart, lib/views/desktop/widgets/DTButton.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/send/send.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart
=> Add cancellation handlers

lib/views/shared/send.dart
=> Avoid opening the file selector multiple times for send screens

.github/workflows/build.yml, integration_test/client/cli_util.dart, lib/views/shared/send.dart, linux/CMakeLists.txt
=> Add IO error handling to the plugin

lib/constants/app_constants.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/receive/widgets/DTReceiveConfirmation.dart, lib/views/desktop/receive/widgets/DTReceivingDone.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTCodeGeneration.dart, lib/views/desktop/send/widgets/DTSendingDone.dart, lib/views/desktop/send/widgets/DTSendingProgress.dart, lib/views/desktop/settings.dart, lib/views/mobile/send/widgets/CodeGeneration.dart, lib/views/shared/send.dart, lib/views/shared/settings.dart, lib/views/shared/util.dart, pubspec.lock
---
OP#699
OP#587
OP#764
OP#761
1- UI fixings and enhancements. 
2- Created SendingDone screen
3- Added no space alert in send.dart
4- Moved canWriteToDirectory to utils file for future use
=> No space alert

lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTErrorUI.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/ReceiveProgress.dart, lib/views/mobile/send/send.dart, lib/views/mobile/send/widgets/SendingProgress.dart, lib/views/mobile/settings.dart, lib/views/widgets/Heading.dart
---
1- Error screens for mobile and desktop are implemented
2-Fixed some text's spacings and fonts
3- Wired up canceling functions with interruption buttons for mobile
OP#675 OP#422 OP#438 OP#437
=> Error screens

lib/views/shared/receive.dart
=> Fixes for windows renaming and memory allocation

lib/constants/app_constants.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTCodeGeneration.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/send/send.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
=> Cancellation and error handling improvements

lib/constants/app_constants.dart, lib/main.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTErrorUI.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/send/send.dart, lib/views/mobile/widgets/ErrorUI.dart, lib/views/shared/receive.dart
=> Add inward buttons

android/.gitignore, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/com/example/dart_wormhole_gui/MainActivity.kt, android/app/src/main/res/xml/fileprovider.xml, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTSelectAFile.dart, lib/views/mobile/send/send.dart, lib/views/shared/file_picker.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart
=> Add Android file picker and stream handling

lib/views/desktop/send/widgets/DTSelectAFile.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart, lib/views/shared/util.dart
=> Fix windows path separator and renaming an open file

lib/constants/app_constants.dart
=> Change configurations to use the TCP relay by default for CI builds

integration_test/client/file_transfer_test.dart, lib/views/desktop/send/widgets/DTSelectAFile.dart, lib/views/shared/receive.dart, lib/views/shared/util.dart, linux/flutter/generated_plugins.cmake, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
=> Update dependencies and fix plugin integration tests

lib/config/routes/routes_desktop_config.dart, lib/config/routes/routes_mobile_config.dart, lib/constants/app_constants.dart, lib/main.dart, lib/main_la.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/send/send.dart, lib/views/desktop/send/widgets/DTErrorUI.dart, lib/views/mobile/introduction-slider.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/EnterCode.dart, lib/views/mobile/receive/widgets/ReceiveProgress.dart, lib/views/mobile/send/send.dart, lib/views/mobile/send/widgets/SendingProgress.dart, lib/views/mobile/widgets/AbortErrorUI.dart, lib/views/mobile/widgets/ErrorUI.dart, lib/views/shared/progress.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart, lib/views/shared/settings.dart, lib/widgets/CodeInputBox.dart, pubspec.lock, pubspec.yaml, test/mobile_widget_test.dart
=> Use change notifiers instead of widget state for transfers

.github/workflows/build.yml, linux/CMakeLists.txt, pubspec.lock, scripts/make_appimage.sh, windows/CMakeLists.txt
=> Linux appimage generation

android/app/src/main/kotlin/com/example/dart_wormhole_gui/MainActivity.kt
=> Fix handling of files from Drive by ensuring they are available

.github/workflows/build.yml, lib/constants/app_constants.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/send/send.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/send/send.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart
=> Interruption copy and state reset

lib/constants/app_constants.dart
=> Update interruption/cancellation copy

.gitmodules, README.md, ios/Runner.xcodeproj/project.pbxproj, macos/Runner/Configs/AppInfo.xcconfig, pubspec.yaml, windows/runner/Runner.rc
Few small changes: get rid of com.example, .gitmodules update to ssh url and main branch and readme update.
Changes should sync with https://github.com/LeastAuthority/dart_wormhole_william/pull/34 
---
=> com.example change to com.leastauthority

.gitignore, .vscode/settings.json, pubspec.yaml
Update publisher information in order to allow MSIX file signing with code signing certificate.
---
=> Update publisher information

android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/com/leastauthority/dart_wormhole_gui/MainActivity.kt, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, lib/views/shared/file_picker.dart, lib/views/shared/send.dart
=> Add handling for SEND intent on Android

lib/views/desktop/settings.dart, lib/views/shared/settings.dart
=> Fix save destination defaults

.github/workflows/build.yml, doc/releases.md, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner/Info.plist, scripts/notarization_config.txt, scripts/notarize.py
=> Add signing configuration for macos release builds

macos/Runner.xcodeproj/project.pbxproj
=> Set correct macos version and enable app sandbox

android/app/src/main/kotlin/com/leastauthority/destiny/FileIOHandler.kt, android/app/src/main/kotlin/com/leastauthority/destiny/MainActivity.kt, android/app/src/main/kotlin/com/leastauthority/destiny/UriReader.kt, android/app/src/main/kotlin/com/leastauthority/destiny/UriWriter.kt, lib/constants/app_constants.dart, lib/views/desktop/receive/receive.dart, lib/views/desktop/receive/widgets/DTReceiveConfirmation.dart, lib/views/mobile/receive/receive.dart, lib/views/mobile/receive/widgets/EnterCode.dart, lib/views/mobile/receive/widgets/ReceiveConfirmation.dart, lib/views/shared/file_picker.dart, lib/views/shared/receive.dart, lib/views/shared/send.dart
=> Add "Save As" button in download confirmation screen

lib/constants/app_constants.dart
Switch from google.com to our repo urls
---
=> set urls to our readme

android/app/src/main/kotlin/com/leastauthority/destiny/FileIOHandler.kt
=> Fix path resolution for nested directories under Downloads on Android

lib/views/shared/receive.dart, lib/views/shared/send.dart
Added small mapping in case of handshake errors
---
=> added in case failed to connect

lib/constants/app_constants.dart, lib/views/shared/util.dart
=> Fix github links and update plugin

lib/constants/app_constants.dart, lib/views/desktop/send/widgets/DTSelectOrDropAFile.dart, lib/views/shared/send.dart
=> Possible race issue

README.md, doc/installation.md
=> Readme update

README.md
=> Updated README.md with Google Play store

.github/workflows/build.yml
Windows version set is not set from tag in Settings page. Default value 1.0.0 is generated.
=> Fix windows version set

.github/workflows/build.yml, android/app/src/main/kotlin/com/leastauthority/destiny/FileIOHandler.kt, android/app/src/main/kotlin/com/leastauthority/destiny/UriReader.kt, macos/Flutter/GeneratedPluginRegistrant.swift, sonar-project.properties
This will add [SonarQube](https://sonar.latfa.net/) based static code analysis and coverage tracking. See details on the [Destiny dashboard](https://sonar.latfa.net/dashboard?id=LeastAuthority_destiny_AYbm07AGpP2j4mdx7SoL).
---
=> add sonar integration

.github/pull_request_template.md
**Related issue(s)**: Closes #241
**Description**:
This is an attempt to invite contributors to use (part of) our pull request template or discard it explicitly.
**Types of changes**:
**Checklist**:
**Thank you!**
=> Rework pull request template with explanations
